package fssi
package ast

import types.exception._
import types.biz._
import bigknife.sop._
import bigknife.sop.macros._
import bigknife.sop.implicits._

import java.io._

@sp trait AccountStore[F[_]] {
  /** Load an account from a json file
    * @param accountFile json file, which was generated by `CreateAccount
    */
  def loadAccountFromFile(accountFile: File): P[F, Either[FSSIException, Account]]

  /** load secret key file from a file
    */
  def loadAccountSecretKeyFile(secretKeyFile: File): P[F, Either[FSSIException, Account.SecretKey]]
}
